export const TRANSLATIONS = {
  es: {
    nav: { features: 'Características', about: 'Nosotros', pricing: 'Beneficios', login: 'Iniciar sesión', register: 'Registrarse', goToAI: 'Ir a la IA', profile: 'Mi Perfil', logout: 'Cerrar sesión' },
    hero: {
      badge: 'Plataforma educativa inteligente',
      title1: 'Aprende sin',
      title2: 'límites con IA',
      subtitle: 'TutorGeist combina inteligencia artificial con educación personalizada para transformar tu forma de aprender.',
      cta: 'Comenzar gratis',
      ctaLogin: 'Probar IA →',
      scroll: 'Descubre más',
    },
    about: {
      badge: 'Quiénes somos',
      title: 'Educación reimaginada para el siglo XXI',
      text1: 'Somos un equipo apasionado por transformar la educación a través de la tecnología. TutorGeist nació con la misión de hacer el aprendizaje accesible, personalizado y efectivo para todos.',
      text2: 'Nuestra plataforma combina modelos de inteligencia artificial de última generación con metodologías pedagógicas probadas para ofrecerte una experiencia educativa única.',
      stat1: 'Estudiantes activos',
      stat2: 'Materias disponibles',
      stat3: 'Países',
    },
    purpose: {
      badge: 'Propósito',
      title: 'Nuestra misión',
      text: 'Democratizar el acceso a una educación de calidad mediante la inteligencia artificial, empoderando a cada estudiante con herramientas personalizadas que se adaptan a su ritmo y estilo de aprendizaje único.',
    },
    benefits: {
      badge: 'Planes',
      title: 'Elige tu camino',
      subtitle: 'Dos opciones diseñadas para potenciar tu aprendizaje',
      card1: {
        name: 'Esencial',
        desc: 'Perfecto para comenzar tu viaje de aprendizaje con IA.',
        features: ['Chat con IA ilimitado', 'Generador de imágenes', 'Acceso a materias base', 'Historial de conversaciones', 'Soporte por email'],
        cta: 'Comenzar',
      },
      card2: {
        name: 'Pro',
        desc: 'Para estudiantes serios que quieren maximizar su potencial.',
        features: ['Todo lo del plan Esencial', 'Generador de código avanzado', 'Biblioteca de recursos premium', 'Análisis de progreso', 'Soporte prioritario 24/7', 'Acceso anticipado a nuevas funciones'],
        cta: 'Ir Pro',
        badge: 'Más popular',
      },
    },
    tryCta: {
      title: '¿Listo para transformar tu aprendizaje?',
      subtitle: 'Únete a miles de estudiantes que ya usan TutorGeist',
      btn: 'Probar IA ahora →',
    },
    profile: {
      title: 'Mi Perfil',
      name: 'Nombre completo',
      email: 'Correo electrónico',
      joined: 'Miembro desde',
      edit: 'Editar perfil',
      save: 'Guardar cambios',
      cancel: 'Cancelar',
      saving: 'Guardando...',
      success: 'Perfil actualizado correctamente',
    },
    footer: {
      copy: '© 2025 TutorGeist. Todos los derechos reservados.',
    },
  },
  en: {
    nav: { features: 'Features', about: 'About', pricing: 'Benefits', login: 'Sign in', register: 'Sign up', goToAI: 'Go to AI', profile: 'My Profile', logout: 'Sign out' },
    hero: {
      badge: 'Intelligent learning platform',
      title1: 'Learn without',
      title2: 'limits with AI',
      subtitle: 'TutorGeist combines artificial intelligence with personalized education to transform the way you learn.',
      cta: 'Start for free',
      ctaLogin: 'Try AI →',
      scroll: 'Discover more',
    },
    about: {
      badge: 'Who we are',
      title: 'Education reimagined for the 21st century',
      text1: 'We are a team passionate about transforming education through technology. TutorGeist was born with the mission to make learning accessible, personalized, and effective for everyone.',
      text2: 'Our platform combines cutting-edge AI models with proven pedagogical methodologies to offer you a unique educational experience.',
      stat1: 'Active students',
      stat2: 'Available subjects',
      stat3: 'Countries',
    },
    purpose: {
      badge: 'Purpose',
      title: 'Our mission',
      text: 'Democratize access to quality education through artificial intelligence, empowering every student with personalized tools that adapt to their unique pace and learning style.',
    },
    benefits: {
      badge: 'Plans',
      title: 'Choose your path',
      subtitle: 'Two options designed to boost your learning',
      card1: {
        name: 'Essential',
        desc: 'Perfect for starting your AI learning journey.',
        features: ['Unlimited AI chat', 'Image generator', 'Access to base subjects', 'Conversation history', 'Email support'],
        cta: 'Get started',
      },
      card2: {
        name: 'Pro',
        desc: 'For serious students who want to maximize their potential.',
        features: ['Everything in Essential', 'Advanced code generator', 'Premium resource library', 'Progress analytics', '24/7 priority support', 'Early access to new features'],
        cta: 'Go Pro',
        badge: 'Most popular',
      },
    },
    tryCta: {
      title: 'Ready to transform your learning?',
      subtitle: 'Join thousands of students already using TutorGeist',
      btn: 'Try AI now →',
    },
    profile: {
      title: 'My Profile',
      name: 'Full name',
      email: 'Email address',
      joined: 'Member since',
      edit: 'Edit profile',
      save: 'Save changes',
      cancel: 'Cancel',
      saving: 'Saving...',
      success: 'Profile updated successfully',
    },
    footer: {
      copy: '© 2025 TutorGeist. All rights reserved.',
    },
  },
  de: {
    nav: { features: 'Funktionen', about: 'Über uns', pricing: 'Vorteile', login: 'Anmelden', register: 'Registrieren', goToAI: 'Zur KI', profile: 'Mein Profil', logout: 'Abmelden' },
    hero: {
      badge: 'Intelligente Lernplattform',
      title1: 'Lerne ohne',
      title2: 'Grenzen mit KI',
      subtitle: 'TutorGeist kombiniert künstliche Intelligenz mit personalisierter Bildung, um deine Lernweise zu transformieren.',
      cta: 'Kostenlos starten',
      ctaLogin: 'KI ausprobieren →',
      scroll: 'Mehr entdecken',
    },
    about: {
      badge: 'Wer wir sind',
      title: 'Bildung neu gedacht für das 21. Jahrhundert',
      text1: 'Wir sind ein Team, das leidenschaftlich daran arbeitet, Bildung durch Technologie zu transformieren. TutorGeist wurde mit der Mission gegründet, Lernen für alle zugänglich, personalisiert und effektiv zu machen.',
      text2: 'Unsere Plattform kombiniert modernste KI-Modelle mit bewährten pädagogischen Methoden, um dir ein einzigartiges Bildungserlebnis zu bieten.',
      stat1: 'Aktive Schüler',
      stat2: 'Verfügbare Fächer',
      stat3: 'Länder',
    },
    purpose: {
      badge: 'Zweck',
      title: 'Unsere Mission',
      text: 'Den Zugang zu hochwertiger Bildung durch künstliche Intelligenz zu demokratisieren und jeden Schüler mit personalisierten Werkzeugen zu stärken, die sich seinem einzigartigen Tempo und Lernstil anpassen.',
    },
    benefits: {
      badge: 'Pläne',
      title: 'Wähle deinen Weg',
      subtitle: 'Zwei Optionen, um dein Lernen zu verbessern',
      card1: {
        name: 'Wesentlich',
        desc: 'Perfekt für den Einstieg in deine KI-Lernreise.',
        features: ['Unbegrenzter KI-Chat', 'Bildgenerator', 'Zugang zu Grundfächern', 'Gesprächsverlauf', 'E-Mail-Support'],
        cta: 'Loslegen',
      },
      card2: {
        name: 'Pro',
        desc: 'Für ernsthafte Schüler, die ihr Potenzial maximieren wollen.',
        features: ['Alles aus Wesentlich', 'Erweiterter Code-Generator', 'Premium-Ressourcenbibliothek', 'Fortschrittsanalyse', '24/7 Prioritätssupport', 'Frühzeitiger Zugang zu neuen Funktionen'],
        cta: 'Pro werden',
        badge: 'Am beliebtesten',
      },
    },
    tryCta: {
      title: 'Bereit, dein Lernen zu transformieren?',
      subtitle: 'Schließ dich Tausenden von Schülern an, die TutorGeist bereits nutzen',
      btn: 'KI jetzt ausprobieren →',
    },
    profile: {
      title: 'Mein Profil',
      name: 'Vollständiger Name',
      email: 'E-Mail-Adresse',
      joined: 'Mitglied seit',
      edit: 'Profil bearbeiten',
      save: 'Änderungen speichern',
      cancel: 'Abbrechen',
      saving: 'Wird gespeichert...',
      success: 'Profil erfolgreich aktualisiert',
    },
    footer: {
      copy: '© 2025 TutorGeist. Alle Rechte vorbehalten.',
    },
  },
};

